### ISSUE TITLE
augmentGCG for other model

### ISSUE THREAD

**Issue by zd82053739099** [OSU-NLP-Group/AmpleGCG#1]
If I want to use the script `run_overgenerate_indiv_query_indiv_model_llama2-chat.sh` to generate adversarial suffixes for other models, such as Qwen or ChatGLM, what modifications should I make?

**Comment by zd82053739099** [comment]
I directly modified the model path, but the results were terrible, with the loss remaining around 1000. There must be other parts that need to be adjusted.

**Comment by lzy37ld** [comment]
@zd82053739099 hey! Sorry for being late.

If you want to apply the scripts to other models, you need to change the [template](https://github.com/OSU-NLP-Group/AmpleGCG/blob/92fbc9a14d40dfaaf5f7f479ef0d56f32c2f93a3/llmattack/llm_attacks/base/attack_manager.py#L138C17-L138C30) you used during the optimization.

For example, they will use different system prompts and you should set the correct system prompt you will use during the inference for your own model of interest.

Let me know if you have other questions.
